/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121008-gf4b044bbe3-20250907"
#endif /* AVUTIL_FFVERSION_H */
